### ISSUE TITLE
How do you compile this?

### ISSUE THREAD

**Issue by LizardLad** [compnerd/eds#1]
I'm on linux and I'm not sure if this is your intended platform but I can't seem to be able to compile this program should I not just be able to excecute g++ on the example?

**Comment by compnerd** [comment]
It is built through autotools.  If you run autogen.bash, that will do the preparation.  After that, the usual, ./configure && make should build it :)  Linux was the original platform where it was written, but, it should work on any host, the major issue being how do you get the raw data, where as on Linux you conveniently have it in sysfs and can also query it through Xrandr.

**Comment by LizardLad** [comment]
Thanks

________________________________

**Comment by compnerd** [comment]
You're welcome!  I just ported the build to CMake which is more common these days.
